version: "3.7"

services:
  provest-database:
    image: postgres
    container_name: provest-database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=pedro
      - POSTGRES_PASSWORD=senhasupersecreta
      - POSTGRES_DB=provest
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local